// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChannelMappings() {
  return window['go']['main']['App']['GetChannelMappings']();
}

export function GetCurrentMIDIPort() {
  return window['go']['main']['App']['GetCurrentMIDIPort']();
}

export function GetMIDIPorts() {
  return window['go']['main']['App']['GetMIDIPorts']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function RemoveChannelMapping(arg1) {
  return window['go']['main']['App']['RemoveChannelMapping'](arg1);
}

export function SetChannelMapping(arg1, arg2) {
  return window['go']['main']['App']['SetChannelMapping'](arg1, arg2);
}

export function SetMIDIPort(arg1) {
  return window['go']['main']['App']['SetMIDIPort'](arg1);
}

export function StartTechno() {
  return window['go']['main']['App']['StartTechno']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
