// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapters} from '../models';

export function GetChannelMappings():Promise<Record<string, number>>;

export function GetCurrentMIDIPort():Promise<number>;

export function GetMIDIPorts():Promise<Array<adapters.MIDIPortInfo>>;

export function Pause():Promise<string>;

export function RemoveChannelMapping(arg1:string):Promise<void>;

export function Resume():Promise<string>;

export function SetChannelMapping(arg1:string,arg2:number):Promise<void>;

export function SetMIDIPort(arg1:number):Promise<void>;

export function StartTechno():Promise<string>;

export function Stop():Promise<string>;
