// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause():Promise<string>;

export function Resume():Promise<string>;

export function StartTechno():Promise<string>;

export function Stop():Promise<string>;
