// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function StartTechno() {
  return window['go']['main']['App']['StartTechno']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
